name: Destroy Infraestrutura

on:
  workflow_dispatch:  # Apenas manualmente

jobs:
  destroy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Inicializar Terraform
        run: |
          cd terraform
          terraform init

      - name: Destruir Infraestrutura
        run: |
          cd terraform
          terraform destroy -auto-approve
